def set_resources box, max_ram=512, max_cpu=1
  box.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--cpus", max_cpu]
    vb.customize ["modifyvm", :id, "--memory", max_ram]
  end
end

Vagrant.configure('2') do |config|
  config.pe_build.download_root = ENV['PE_BUILD_DOWNLOAD_ROOT']
  config.ssh.insert_key = false
  # This is the box name used by the setup helpers in the acceptance tests.
  config.vm.box = 'centos'

  config.vm.define 'pe-3x' do |node|
    node.vm.hostname = 'pe-3x.pe-bootstrap.vlan'
    # All-in-one master nodes need a generous amount of RAM for all the Java.
    set_resources node, 4096, 1

    node.vm.provision :pe_bootstrap do |p|
      p.version = '3.8.7'
      p.role = :master
    end
  end

  config.vm.define 'pe-latest' do |node|
    node.vm.hostname = 'pe-latest.pe-bootstrap.vlan'
    # All-in-one master nodes need a generous amount of RAM for all the Java.
    set_resources node, 4096, 1

    node.vm.provision :pe_bootstrap do |p|
      p.version_file  = 'LATEST_3x'
      p.role = :master
    end
  end
end
