# NOTE: This acceptance suite starts off at 2016.2.0 as the installation
# workflow changed in that release.
def set_resources box, max_ram=512, max_cpu=1
  box.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--cpus", max_cpu]
    vb.customize ["modifyvm", :id, "--memory", max_ram]
  end
end

Vagrant.configure('2') do |config|
  config.pe_build.download_root = ENV['PE_BUILD_DOWNLOAD_ROOT']
  config.ssh.insert_key = false

  config.vm.define 'pe-20164-master' do |node|
    node.vm.hostname = 'pe-20164-master.pe-bootstrap.vlan'
    node.vm.box      = 'centos'
    # All-in-one master nodes need a generous amount of RAM for all the Java.
    set_resources node, 4096, 1
    node.vm.provision :shell, :inline => "service iptables stop || true\niptables -F || true"

    node.vm.network 'private_network', :ip => '10.20.1.102'
    node.vm.provision :shell, :inline => 'echo "10.20.1.103 pe-20164-agent.pe-bootstrap.vlan" >> /etc/hosts'

    node.vm.provision :pe_bootstrap do |p|
      p.version = '2016.4.11'
      p.role = :master
      # Set autosign to false so that we can test pe_agent functionality.
      p.autosign = false
    end
  end

  config.vm.define 'pe-20164-agent' do |node|
    node.vm.hostname = 'pe-20164-agent.pe-bootstrap.vlan'
    node.vm.box      = 'ubuntu'

    node.vm.network 'private_network', :ip => '10.20.1.103'
    node.vm.provision :shell, :inline => 'echo "10.20.1.102 pe-20164-master.pe-bootstrap.vlan" >> /etc/hosts'

    node.vm.provision :pe_agent do |p|
      p.master_vm = 'pe-20164-master'
    end
  end

  config.vm.define 'pe-2016latest-master' do |node|
    node.vm.hostname = 'pe-2016latest-master.pe-bootstrap.vlan'
    node.vm.box      = 'centos'
    # All-in-one master nodes need a generous amount of RAM for all the Java.
    set_resources node, 4096, 1
    node.vm.provision :shell, :inline => "service iptables stop || true\niptables -F || true"

    node.vm.network 'private_network', :ip => '10.20.1.104'
    node.vm.provision :shell, :inline => 'echo "10.20.1.105 pe-2016latest-agent.pe-bootstrap.vlan" >> /etc/hosts'

    node.vm.provision :pe_bootstrap do |p|
      p.version_file = 'LATEST'
      p.role = :master
      # Set autosign to false so that we can test pe_agent functionality.
      p.autosign = false
    end
  end

  config.vm.define 'pe-2016latest-agent' do |node|
    node.vm.hostname = 'pe-2016latest-agent.pe-bootstrap.vlan'
    node.vm.box      = 'ubuntu'

    node.vm.network 'private_network', :ip => '10.20.1.105'
    node.vm.provision :shell, :inline => 'echo "10.20.1.104 pe-2016latest-master.pe-bootstrap.vlan" >> /etc/hosts'

    node.vm.provision :pe_agent do |p|
      p.master_vm = 'pe-2016latest-master'
    end
  end
end
